apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
  labels:
    app: config-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-deployment
  template:
    metadata:
      labels:
        app: config-deployment
    spec:
      containers:
        - name: config
          image: holyadio/kubernetes-config
          ports:
            - containerPort: 8081

---
#Service
apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  selector:
    app: config-deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer