---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  labels:
    app: eureka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-deployment
  template:
    metadata:
      labels:
        app: eureka-deployment
    spec:
      containers:
        - name: eureka
          image: holyadio/kubernetes-eureka
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081

---
#Service
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  selector:
    app: eureka-deployment
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer